### ISSUE TITLE
Document Manager issues

### ISSUE THREAD

**Issue by takeit** [sulu-io/sulu-document-manager#57]
Hello, 

I really like the idea of the sulu document manager and I want to try it out and use it in my project althought I found it really complex to configure it even after reading the [documentation](http://docs.sulu.io/en/latest/reference/components/document-manager/index.html).

I have some questions and issues though. 
- what consequences this library give, are there any?
- would that require some extra logic to support multilingual websites?
- it gives me an error `The option "path" does not exist. Defined options are: locale` when doing: 

``` php
$this->documentManager->persist($document, 'en', [
    'path' => $homePath,
]);
```

during the repository initialization. (I have configured it using [this config](https://github.com/sulu-io/sulu-document-manager/tree/master/symfony-di) and I looked how it's configured in Sulu cms itself.)

What am I missing?

Best,

**Comment by dantleech** [comment]
> what consequences this library give, are there any?

If you mean benefits, f.e. over the [PHPCR-ODM](https://github.com/doctrine/phpcr-odm), to name a couple:
- It preserves the order of operations - the PHPCR-ODM always executes UPDATE, INSERT, DELETE in a predefined order, making some operations impossible (or at least very hard and hacky).
- It allows a greater degree of control over the PHPCR property names, including namespaces.

The thing to understand is that it does not act like a standard ORM. You must call `->persist` _every time_ you change a document - `persist` here is more like flashing the document to the PHPCR node.

> would that require some extra logic to support multilingual websites?

I don't think you need any extra logic to support multilang, Sulu proper extends the document manager quite alot, but I think the essential multilang handling is present here.

> it gives me an error The option "path" does not exist. Defined options are: locale when doing:

Hmm, the [functional tests](https://github.com/sulu-io/sulu-document-manager/blob/master/tests/Functional/DocumentManager/MappingTest.php#L59) work. Make sure that the `ExplicitSubscriber` is registered with the EventSubscriber that is used by the `DocumentManager`.

**Comment by takeit** [comment]
> Hmm, the functional tests work. Make sure that the ExplicitSubscriber is registered with the EventSubscriber that is used by the DocumentManager.

You were right, works now. Thanks for the explanation.
